# Generated by Django 5.0.4 on 2024-05-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CB7_STATUS', models.IntegerField()),
                ('CB7_FILIAL', models.IntegerField()),
                ('CB7_ORDSEP', models.IntegerField()),
                ('CB7_PEDIDO', models.IntegerField()),
                ('CB7_CLIENT', models.CharField(max_length=6)),
                ('CB7_LOJA', models.IntegerField()),
                ('A1_NOME', models.CharField(max_length=50)),
                ('CB7_DTEMIS', models.IntegerField()),
                ('CB7_HREMIS', models.CharField(max_length=5)),
                ('CB7_DTINIS', models.IntegerField()),
                ('CB7_HRINIS', models.CharField(max_length=5)),
                ('CB7_DTFIMS', models.IntegerField()),
                ('CB7_HRFIMS', models.CharField(max_length=5)),
                ('CB7_NOTA', models.IntegerField()),
                ('CB7_SERIE', models.IntegerField()),
                ('CB8_PROD', models.BigIntegerField()),
                ('B1_DESC', models.CharField(max_length=50)),
            ],
        ),
    ]
