# Generated by Django 5.0.6 on 2024-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_produto_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='CB7_STATUS',
            field=models.IntegerField(),
        ),
    ]
