# Generated by Django 5.0.6 on 2024-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_produto_cb7_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='CB7_ORDSEP',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
